exchange:
  name: "binance"
  testnet: true

data:
  api_key: ""
  api_secret: ""
  cache_dir: "data/cache"
  database: "data/market_data.db"

trading:
  symbol: "BTCUSDT"
  interval: "15m"
  base_currency: "BTC"
  quote_currency: "USDT"

strategies:
  ma_crossover:
    short_window: 10
    long_window: 20

  rsi:
    period: 14
    oversold: 30
    overbought: 70

  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9

  bollinger:
    window: 20
    std_dev: 2.0
    entry_threshold: 1.0
    exit_threshold: 0.5

  supertrend_ichimoku_dmi:
    # SuperTrend 파라미터
    st_ichi_multiplier: 1.0
    st_ichi_length: 8
    st_dmi_multiplier: 1.0
    st_dmi_length: 8
    
    # DMI 파라미터
    dmi_length: 14
    adx_smoothing: 14
    strong_trend: 25
    weak_trend: 20
    
    # Ichimoku 파라미터
    conversion_periods: 9
    base_periods: 26
    lagging_span2_periods: 52
    displacement: 26

    # RSI 파라미터
    rsi_length: 10
    rsi_overbought: 75
    rsi_oversold: 25

    # Stochastic 파라미터
    stoch_k: 14
    stoch_d: 3
    stoch_smooth: 3
    stoch_overbought: 80
    stoch_oversold: 20

    # MACD 파라미터
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9

    # 리스크 관리 파라미터
    stop_loss_atr: 0.8
    take_profit_atr: 1.6
    trailing_stop_atr: 1.2
    max_risk_per_trade: 0.02

risk_management:
  risk_per_trade: 0.01 # 1%
  max_leverage: 3
  margin_ratio: 0.1 # 10%
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
  trailing_stop_start: 0.01 # 1%

backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_balance: 1000000
  commission: 0.001 # 0.1%

simulation:
  initial_balance: 1000
  commission_rate: 0.001 # 0.1%

logging:
  level: "INFO"
  file: "logs/trading.log"

database:
  path: "data/market_data.db"
  cache_size: 1000
